export const ASTRONAUT = 'ASTRONAUTS';
export const ASTRONAUT_BY_ID = 'ASTRONAUT_BY_ID';
export const ASTRONAUT_CURR_PAGE = 'ASTRONAUT_CURR_PAGE';

export const AGENCIES = 'AGENCIES';
export const AGENCY_BY_ID = 'AGENCY_BY_ID';